// ImagesLoader.js
// Cache buster for CloudFront - change this on each deploy to force fresh image loads
import { GALLERY_PATHS, IMAGE_EXT } from "./config/gallery";

const CACHE_VERSION = "v2025-10-11-fix3";
const withCacheBust = (path) => `${path}?v=${CACHE_VERSION}`;

const {
  LOCANDA_GALLERY,
  LOCANDA_OPEN,
  OSTERIA_GALLERY,
  OSTERIA_OPEN,
  RISTORANTE_GALLERY,
  RISTORANTE_OPEN,
  VILLA_FORNACA_GALLERY,
  VILLA_FORNACA_OPEN,
  VILLA_PIEVE_GALLERY,
} = GALLERY_PATHS;

const LocandaDelGlicineGallery = [
  `${LOCANDA_GALLERY}/LDC12${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC13${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC14${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC15${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC16${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC17${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC18${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC19${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC20${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC21${IMAGE_EXT}`,
  `${LOCANDA_GALLERY}/LDC22${IMAGE_EXT}`,
].map(withCacheBust);

const LocandaDelGlicineOpen = [
  `${LOCANDA_OPEN}/LDC1${IMAGE_EXT}`,
  `${LOCANDA_OPEN}/LDC2${IMAGE_EXT}`,
  `${LOCANDA_OPEN}/LDC5${IMAGE_EXT}`,
  `${LOCANDA_OPEN}/LDC8${IMAGE_EXT}`,
  `${LOCANDA_OPEN}/LDC9${IMAGE_EXT}`,
  `${LOCANDA_OPEN}/LDC10${IMAGE_EXT}`,
].map(withCacheBust);

const LaRimmesaGallery = [
  `${OSTERIA_GALLERY}/La-Rimessa73${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa83${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa93${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa103${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa113${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa123${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa133${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa143${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa153${IMAGE_EXT}`,
  `${OSTERIA_GALLERY}/La-Rimessa163${IMAGE_EXT}`,
].map(withCacheBust);

const LaRimmesaOpen = [
  `${OSTERIA_OPEN}/La-Rimessa1${IMAGE_EXT}`,
  `${OSTERIA_OPEN}/La-Rimessa2${IMAGE_EXT}`,
  `${OSTERIA_OPEN}/La-Rimessa3${IMAGE_EXT}`,
  `${OSTERIA_OPEN}/La-Rimessa4${IMAGE_EXT}`,
  `${OSTERIA_OPEN}/La-Rimessa5${IMAGE_EXT}`,
  `${OSTERIA_OPEN}/La-Rimessa6${IMAGE_EXT}`,
].map(withCacheBust);

const RistoranteIlGlicineGallery = [
  `${RISTORANTE_GALLERY}/IMG_0568${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0577${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0578${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0580${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0581${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0582${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0583${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0584${IMAGE_EXT}`,
  `${RISTORANTE_GALLERY}/IMG_0588${IMAGE_EXT}`,
].map(withCacheBust);

const RistoranteIlGlicineOpen = [
  `${RISTORANTE_OPEN}/IMG_0565${IMAGE_EXT}`,
  `${RISTORANTE_OPEN}/IMG_0569${IMAGE_EXT}`,
  `${RISTORANTE_OPEN}/IMG_0586${IMAGE_EXT}`,
  `${RISTORANTE_OPEN}/IMG_0589${IMAGE_EXT}`,
].map(withCacheBust);

const VillaLaFornacaGallery = [
  `${VILLA_FORNACA_GALLERY}/La-fornaca7${IMAGE_EXT}`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca8${IMAGE_EXT}`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca9${IMAGE_EXT}`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca10.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca11.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca12.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca13.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca14.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca15.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca16.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca17.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca18.png`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca19${IMAGE_EXT}`,
  `${VILLA_FORNACA_GALLERY}/La-fornaca20${IMAGE_EXT}`,
].map(withCacheBust);

const VillaLaFornacaOpen = [
  `${VILLA_FORNACA_OPEN}/La-fornaca1${IMAGE_EXT}`,
  `${VILLA_FORNACA_OPEN}/La-fornaca2${IMAGE_EXT}`,
  `${VILLA_FORNACA_OPEN}/La-fornaca3${IMAGE_EXT}`,
  `${VILLA_FORNACA_OPEN}/La-fornaca4${IMAGE_EXT}`,
  `${VILLA_FORNACA_OPEN}/La-fornaca5${IMAGE_EXT}`,
  `${VILLA_FORNACA_OPEN}/La-fornaca6${IMAGE_EXT}`,
].map(withCacheBust);

const VillaPieveVecchiaGallery = [
  `${VILLA_PIEVE_GALLERY}/20240721_193110${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/20240721_193225${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/20240721_193317${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0001${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0003${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0005${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0006${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0007${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0008${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0009${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0010${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0012${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0013${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0014${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0015${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0016${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0017${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0018${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0019${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0027${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0037${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0039${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0045${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0048${IMAGE_EXT}`,
].map(withCacheBust);

const VillaPieveVecchiaOpen = [
  `${VILLA_PIEVE_GALLERY}/20240721_193110${IMAGE_EXT}`,
  `${VILLA_PIEVE_GALLERY}/IMG-20240810-WA0001${IMAGE_EXT}`,
].map(withCacheBust);

export {
  LocandaDelGlicineGallery,
  LocandaDelGlicineOpen,
  LaRimmesaGallery,
  LaRimmesaOpen,
  RistoranteIlGlicineGallery,
  RistoranteIlGlicineOpen,
  VillaLaFornacaGallery,
  VillaLaFornacaOpen,
  VillaPieveVecchiaGallery,
  VillaPieveVecchiaOpen,
};
